spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        defer-datasource-initialization: true
        default_batch_fetch_size: 30
        use_sql_comments: true
        format_sql: true
    open-in-view: false
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        region: ap-northeast-2
        bucket: ${S3_BUCKET}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

kakao:
  rest-api-key: ${KAKAO_MAP_REST_API_KEY}
  app-id: ${KAKAO_APP_ID}
  admin-key: ${KAKAO_ADMIN_KEY}

apple:
  client-id: ${APPLE_CLIENT_ID}
  key-id: ${APPLE_KEY_ID}
  team-id: ${APPLE_TEAM_ID}
  sign-key: ${APPLE_PRIVATE_KEY}

jwt:
  issuer: ${JWT_ISSUER}
  secret_key: ${JWT_SECRET_KEY}

slack:
  url: ${SLACK_URL}

---

spring:
  config:
    activate:
      on-profile: dev
    import: aws-parameterstore:/config/photospot_dev/

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  cloud:
    aws:
      credentials:
        instance-profile: true
        access-key:
        secret-key:
